version: '3.8'
services:
  db:
    image: postgres:15
    container_name: agoom_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-agoom}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: arbormed_translate
    restart: always
    ports:
      - "5005:5000"
    environment:
      - LT_LOAD_ONLY=en,hu
      - LT_HOST=0.0.0.0

volumes:
  pgdata:
